'use client';

import { useEffect, useRef, useState, type CSSProperties } from 'react';
import type { SalvageLedger, SalvageReport } from '@/salvage/types';
import { dollars, hostOf } from '../inspect-format';
import { lotFooterSentence } from '../assessments/format';
import { CeilingLadder } from './ceiling-ladder';
import { CompsTable } from './comps-table';
import { EvidenceChip, ProgramTable } from './program-table';
import { VerdictBanner } from './report';

// The finished salvage assessment, organized for traversal (DESIGN.md):
// the verdict and the numbers strip answer the bid question in five
// seconds; the ceiling ladder shows why the number is what it is; the
// sensitivity rows say what would change it; the comps and program tables
// let the reader falsify every input. A sticky index knows where you are.
// Verdict, numbers, ladder, dealbreakers, and what-people-miss never collapse.

const SECTIONS = [
  { id: 'ceiling', label: 'ceiling' },
  { id: 'sensitivity', label: 'what would change it' },
  { id: 'comps', label: 'comps' },
  { id: 'plan', label: 'repair programs' },
  { id: 'costs', label: 'every line' },
  { id: 'damage', label: 'damage' },
  { id: 'missed', label: 'missed' },
  { id: 'history', label: 'history' },
  { id: 'bid', label: 'before you bid' },
] as const;

export function SalvageReportView({
  report,
  choreograph,
  onAnchor,
}: {
  report: SalvageReport;
  choreograph: boolean;
  onAnchor: (indices: number[]) => void;
}) {
  const { lot, triage, plan, ledger, research, sightings, vinCheck, assessment, stages } = report;
  const degraded = stages.filter((s) => !s.ok);
  const footer = lotFooterSentence(lot, ledger?.feesScheduleDate);

  let sectionIndex = 0;
  const reveal = (): CSSProperties & Record<'--reveal-delay', string> => ({
    ['--reveal-delay']: `${sectionIndex++ * 60}ms`,
  });

  // The banner headline is the action itself: the number to bid to, or the
  // refusal. Legacy plays render their old words.
  const headline = {
    build: {
      tone: 'pass' as const,
      label: ledger?.ceiling ? `BID TO ${dollars(ledger.ceiling)}` : 'BID',
    },
    walk: { tone: 'avoid' as const, label: 'NO BID' },
    part_out: { tone: 'caution' as const, label: 'PART OUT (LEGACY)' },
    parts_car: { tone: 'caution' as const, label: 'DONOR ONLY (LEGACY)' },
    watch: { tone: 'caution' as const, label: 'UNSETTLED (LEGACY)' },
  }[assessment.verdict];

  return (
    <div className={`flex flex-col gap-8 ${choreograph ? 'choreograph' : ''}`}>
      <div className="reveal" style={reveal()}>
        <VerdictBanner
          verdict={headline.tone}
          label={headline.label}
          summary={assessment.summary}
        />
        <p className="type-meta mt-1 font-mono">
          lot {lot.lotNumber} · {lot.location} ·{' '}
          {lot.saleDate ? `sale ${lot.saleDate}` : 'future sale'} · title: {lot.titleBrand}
          {lot.currentBid ? ` · bid at collection ${dollars(lot.currentBid)}` : ''}
        </p>
        {report.legacy && (
          <p className="type-meta mt-2">
            report generated by an earlier model; run the lot again for the ceiling
          </p>
        )}
      </div>

      {ledger && (
        <div className="reveal" style={reveal()}>
          <NumbersStrip ledger={ledger} />
        </div>
      )}

      {assessment.dealbreakers.length > 0 && (
        <section className="reveal flex flex-col gap-2" style={reveal()}>
          {assessment.dealbreakers.map((d, i) => (
            <p key={i} className="type-body border-l-2 border-danger pl-3 text-danger">
              {d}
            </p>
          ))}
        </section>
      )}

      {!report.legacy && <ReportIndex ledger={ledger} />}

      {ledger?.exit && (
        <section id="ceiling" className="reveal flex flex-col gap-3 scroll-mt-14" style={reveal()}>
          <h3 className="type-h2">The ceiling ladder</h3>
          <CeilingLadder ledger={ledger} />
          {ledger.ceiling !== null && ledger.ceiling <= 0 && ledger.unlocks.length > 0 && (
            <div className="flex flex-col gap-1">
              <p className="type-label">what would have to be true</p>
              {[...ledger.unlocks]
                .sort((a, b) => Number(b.feasible) - Number(a.feasible))
                .map((u) => (
                  <p key={u.id} className={`type-meta ${u.feasible ? '' : 'text-faint'}`}>
                    {u.feasible ? '' : 'not in reach: '}
                    {u.note}
                  </p>
                ))}
            </div>
          )}
          <p className="type-meta">exit: {ledger.exit.basis}</p>
        </section>
      )}

      {ledger && liveSensitivity(ledger).length > 0 && (
        <section
          id="sensitivity"
          className="reveal flex flex-col gap-3 scroll-mt-14"
          style={reveal()}
        >
          <h3 className="type-h2">What would change the answer</h3>
          <SensitivityRows ledger={ledger} />
        </section>
      )}

      {ledger && (ledger.exit?.comps.length || ledger.wreck?.comps.length) ? (
        <section id="comps" className="reveal flex flex-col gap-4 scroll-mt-14" style={reveal()}>
          <h3 className="type-h2">The comps</h3>
          {ledger.exit && <CompsTable label="exit comps" comps={ledger.exit.comps} />}
          {ledger.wreck && <CompsTable label="wreck market" comps={ledger.wreck.comps} />}
          {ledger.wreck && <p className="type-meta">{ledger.wreck.basis}</p>}
        </section>
      ) : null}

      {plan.programs.length > 0 && (
        <section id="plan" className="reveal scroll-mt-14" style={reveal()}>
          <details className="group" open>
            <summary className="cursor-pointer list-none [&::-webkit-details-marker]:hidden">
              <h3 className="type-h2 inline">Repair programs</h3>{' '}
              <span className="type-meta ml-2 font-mono">
                {plan.programs.length} programs · {plan.lines.length} lines · {dollars(plan.low)}–
                {dollars(plan.high)} · expected {dollars(plan.expected)} · {plan.diyHoursTotal}h of
                your labor · <span className="text-accent group-open:hidden">expand</span>
                <span className="hidden text-accent group-open:inline">collapse</span>
              </span>
            </summary>
            <div className="mt-3">
              <ProgramTable plan={plan} onAnchor={onAnchor} />
            </div>
          </details>
        </section>
      )}

      {ledger && (
        <section id="costs" className="reveal scroll-mt-14" style={reveal()}>
          <details className="group">
            <summary className="cursor-pointer list-none [&::-webkit-details-marker]:hidden">
              <h3 className="type-h2 inline">Every line</h3>{' '}
              <span className="type-meta ml-2 font-mono">
                {ledger.costs.length} cost lines · fees at{' '}
                {ledger.ceiling ? `the ${dollars(ledger.ceiling)} ceiling` : 'no bid'} ·{' '}
                <span className="text-accent group-open:hidden">expand</span>
                <span className="hidden text-accent group-open:inline">collapse</span>
              </span>
            </summary>
            <div className="mt-3">
              <CostTable ledger={ledger} />
            </div>
          </details>
        </section>
      )}

      <section id="damage" className="reveal flex flex-col gap-3 scroll-mt-14" style={reveal()}>
        <h3 className="type-h2">What&apos;s broken</h3>
        <DamageList triage={triage} onAnchor={onAnchor} />
        <p className="type-meta">
          airbags {triage.airbagsDeployed} · flood{' '}
          {triage.floodEvidence ? 'evidence seen' : 'not seen'} · fire{' '}
          {triage.fireEvidence ? 'evidence seen' : 'not seen'} · drivetrain: {triage.drivetrainRisk}
        </p>
      </section>

      {plan.missed.length > 0 && (
        <section id="missed" className="reveal flex flex-col gap-2 scroll-mt-14" style={reveal()}>
          <h3 className="type-h2">What people miss</h3>
          <ul className="flex flex-col gap-2">
            {plan.missed.map((item, i) => (
              <li key={i} className="type-body flex max-w-[72ch] gap-2">
                <span className="text-warn">·</span>
                <span>{item}</span>
              </li>
            ))}
          </ul>
        </section>
      )}

      {research.length > 0 && (
        <section className="reveal scroll-mt-14" style={reveal()}>
          <details className="group">
            <summary className="cursor-pointer list-none [&::-webkit-details-marker]:hidden">
              <h3 className="type-h2 inline">Research notes</h3>{' '}
              <span className="type-meta ml-2 font-mono">
                {research.length} cited note{research.length === 1 ? '' : 's'} ·{' '}
                <span className="text-accent group-open:hidden">expand</span>
                <span className="hidden text-accent group-open:inline">collapse</span>
              </span>
            </summary>
            <div className="mt-3 flex flex-col gap-3">
              {research.map((finding, i) => (
                <div key={i} className="flex flex-col gap-1">
                  <p className="type-body max-w-[72ch]">{finding.summary}</p>
                  <div className="flex flex-wrap gap-x-4 gap-y-1">
                    {finding.sources.map((s) => (
                      <a
                        key={s.url}
                        href={s.url}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="type-meta font-mono text-faint transition-colors duration-[120ms] ease-out hover:text-accent"
                      >
                        {hostOf(s.url)}
                      </a>
                    ))}
                  </div>
                </div>
              ))}
            </div>
          </details>
        </section>
      )}

      {vinCheck && (
        <section id="history" className="reveal flex flex-col gap-3 scroll-mt-14" style={reveal()}>
          <h3 className="type-h2">History &amp; provenance</h3>
          <p className="font-mono text-[13px]">{vinCheck.vin}</p>
          {vinCheck.decoded && (
            <p className="type-body text-dim">
              {[
                vinCheck.decoded.make,
                vinCheck.decoded.model,
                vinCheck.decoded.year,
                vinCheck.decoded.bodyClass,
                vinCheck.decoded.engine,
                vinCheck.decoded.plant,
              ]
                .filter(Boolean)
                .join(' · ')}
            </p>
          )}
          {vinCheck.mismatches.map((m, i) => (
            <p key={i} className="type-body border-l-2 border-danger pl-3 text-danger">
              {m}
            </p>
          ))}
          {sightings.length > 0 && (
            <ol className="flex flex-col gap-2">
              {sightings.map((s) => (
                <li key={s.url} className="border-l-2 border-border-strong pl-3">
                  <div className="flex flex-wrap items-baseline gap-x-3">
                    <a
                      href={s.url}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="type-body transition-colors duration-[120ms] ease-out hover:text-accent"
                    >
                      {s.title}
                    </a>
                    <span className="type-meta font-mono">
                      {s.source}
                      {s.date ? ` · ${s.date}` : ''}
                    </span>
                  </div>
                  {s.note && <p className="type-body mt-0.5 text-dim">{s.note}</p>}
                </li>
              ))}
            </ol>
          )}
          <div className="flex flex-col gap-1">
            <p className="type-meta">{vinCheck.note}</p>
            <div className="flex flex-wrap gap-x-4 gap-y-1">
              {vinCheck.links.map((link) => (
                <a
                  key={link.url}
                  href={link.url}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="type-meta font-mono text-faint transition-colors duration-[120ms] ease-out hover:text-accent"
                >
                  {link.label}
                </a>
              ))}
            </div>
          </div>
        </section>
      )}

      {assessment.watchItems.length > 0 && (
        <section id="bid" className="reveal flex flex-col gap-2 scroll-mt-14" style={reveal()}>
          <h3 className="type-h2">Before you bid</h3>
          <ul className="flex flex-col gap-1">
            {assessment.watchItems.map((item, i) => (
              <li key={i} className="type-body flex max-w-[72ch] gap-2">
                <span className="text-faint">·</span>
                <span>{item}</span>
              </li>
            ))}
          </ul>
        </section>
      )}

      {degraded.length > 0 && (
        <section
          className="reveal flex flex-col gap-1 border-t border-border pt-3"
          style={reveal()}
        >
          {degraded.map((status, i) => (
            <p key={i} className="type-meta">
              {status.stage} unavailable{status.detail ? `: ${status.detail}` : ''}
            </p>
          ))}
        </section>
      )}

      {/* The sentence is built where it can be tested; only the source is a
          link, and only when the lot has a page to open (SPEC 61). */}
      <p className="type-meta border-t border-border pt-3">
        {footer.lead}
        {footer.href ? (
          <a
            href={footer.href}
            target="_blank"
            rel="noopener noreferrer"
            className="text-faint transition-colors duration-[120ms] ease-out hover:text-accent"
          >
            {footer.source}
          </a>
        ) : (
          footer.source
        )}
        {footer.tail}
      </p>
    </div>
  );
}

// DESIGN.md numbers strip: the five-second answer. Missing numbers render
// an en dash with the reason — absence is information. The ceiling cell is
// the only accent, and only when there is a ceiling to bid to.
function NumbersStrip({ ledger }: { ledger: SalvageLedger }) {
  const exit = ledger.exit;
  const ceiling = ledger.ceiling;
  return (
    <div className="flex flex-col gap-1">
      <div className="grid grid-cols-1 gap-px overflow-hidden rounded-[4px] border border-border bg-border sm:grid-cols-3">
        <Cell
          label="bid ceiling"
          value={ceiling === null ? undefined : ceiling > 0 ? dollars(ceiling) : '$0'}
          note={
            ceiling === null
              ? 'no exit anchor to solve against'
              : ceiling > 0
                ? `all-in ${dollars(ledger.allInAtCeiling ?? 0)} ≤ ${Math.round(ledger.discipline.share * 100)}% of the low exit`
                : `${ledger.killers[0]?.label.toLowerCase() ?? 'the costs'} eat the exit`
          }
          accent={ceiling !== null && ceiling > 0}
          danger={ceiling === 0}
        />
        <Cell
          label="break-even · the wall"
          value={ledger.breakEven === null ? undefined : dollars(ledger.breakEven)}
          note={
            ledger.breakEven === null
              ? 'needs an exit'
              : `no margin at all · stress ${ledger.stress !== null ? dollars(ledger.stress) : '–'} if every repair hits its high`
          }
        />
        <Cell
          label="rebuilt exit · low · typical"
          value={exit ? `${dollars(exit.low)} · ${dollars(exit.typical)}` : undefined}
          note={
            exit
              ? `${exit.n} comp${exit.n === 1 ? '' : 's'} · ${exit.lane.replace(/_/g, ' ')}${exit.thin ? ' · thin' : ''}`
              : 'no clean or rebuilt comps, no stated ACV'
          }
        />
      </div>
      <p className="type-meta">
        {ledger.wreck
          ? `wreck market: ${dollars(ledger.wreck.low)}–${dollars(ledger.wreck.high)}, median ${dollars(ledger.wreck.median)} over ${ledger.wreck.n} lot${ledger.wreck.n === 1 ? '' : 's'} (${ledger.wreck.nSold} sold) · context, not a verdict input`
          : 'wreck market: no salvage-auction results found for this model'}
        {' · '}
        discipline: {ledger.discipline.basis.split(';')[0]}
      </p>
    </div>
  );
}

function Cell({
  label,
  value,
  note,
  accent,
  danger,
}: {
  label: string;
  value?: string;
  note: string;
  accent?: boolean;
  danger?: boolean;
}) {
  return (
    <div className="bg-surface p-4">
      <div className="type-label">{label}</div>
      <div
        className={`mt-1 font-mono text-[20px] font-semibold tabular-nums ${accent ? 'text-accent' : danger ? 'text-danger' : ''}`}
      >
        {value ?? '–'}
      </div>
      <div className="type-meta mt-0.5">{note}</div>
    </div>
  );
}

// DESIGN.md sensitivity rows: label, ceiling under that assumption, delta
// with its sign, the assumption's numbers in meta. No color on numbers.
// At a zero ceiling, a row that stays at zero says nothing the unlocks did
// not; only rows that move render.
function liveSensitivity(ledger: SalvageLedger) {
  return ledger.sensitivity.filter((r) => (ledger.ceiling ?? 0) > 0 || (r.ceiling ?? 0) > 0);
}

function SensitivityRows({ ledger }: { ledger: SalvageLedger }) {
  const signed = (n: number) => (n < 0 ? `−${dollars(Math.abs(n))}` : `+${dollars(n)}`);
  return (
    <div className="flex flex-col">
      {liveSensitivity(ledger).map((row) => (
        <div
          key={row.id}
          className="grid grid-cols-[minmax(0,1fr)_5.5rem_5.5rem] items-baseline gap-x-3 border-b border-border py-1.5"
        >
          <div className="min-w-0">
            <p className="type-spec truncate text-dim">{row.label}</p>
            <p className="type-meta">{row.note}</p>
          </div>
          <span className="font-mono text-[13px] tabular-nums text-right">
            {row.ceiling === null ? '–' : dollars(row.ceiling)}
          </span>
          <span className="font-mono text-[13px] tabular-nums text-right text-dim">
            {row.delta === null ? '' : signed(row.delta)}
          </span>
        </div>
      ))}
    </div>
  );
}

// Every cost line with its basis: the ledger the ladder rolls up.
function CostTable({ ledger }: { ledger: SalvageLedger }) {
  return (
    <div className="flex flex-col gap-3">
      <div className="flex flex-col font-mono text-[12px]">
        <div className="grid grid-cols-[minmax(0,1fr)_5rem_5rem_5rem_4.5rem] gap-x-2 border-b border-border py-1 text-right">
          <span className="type-meta text-left">line</span>
          <span className="type-meta">low</span>
          <span className="type-meta">expected</span>
          <span className="type-meta">high</span>
          <span className="type-meta">basis</span>
        </div>
        {ledger.costs.map((line) => (
          <div
            key={line.id}
            className="flex flex-col border-b border-border py-1.5"
            title={line.basis}
          >
            <div className="grid grid-cols-[minmax(0,1fr)_5rem_5rem_5rem_4.5rem] items-baseline gap-x-2 text-right tabular-nums">
              <span className="truncate text-left text-dim">{line.label}</span>
              <span className="text-faint">{dollars(line.low)}</span>
              <span>{dollars(line.expected)}</span>
              <span className="text-faint">{dollars(line.high)}</span>
              <span className="flex justify-end">
                <EvidenceChip evidence={line.evidence} />
              </span>
            </div>
          </div>
        ))}
      </div>
      <p className="type-meta">
        expected values drive the ceiling; hover a line for its basis · your labor {ledger.diyHours}
        h at $0
      </p>
    </div>
  );
}

// DESIGN.md report index: a sticky line of text that knows where you are.
function ReportIndex({ ledger }: { ledger?: SalvageLedger }) {
  const sections = SECTIONS.filter((s) => {
    if (s.id === 'ceiling') return Boolean(ledger?.exit);
    if (s.id === 'sensitivity') return Boolean(ledger) && liveSensitivity(ledger!).length > 0;
    if (s.id === 'comps') return Boolean(ledger?.exit?.comps.length || ledger?.wreck?.comps.length);
    if (s.id === 'costs') return Boolean(ledger);
    return true;
  });
  const [active, setActive] = useState<string>(sections[0]?.id ?? 'damage');
  const observer = useRef<IntersectionObserver | null>(null);

  useEffect(() => {
    observer.current = new IntersectionObserver(
      (entries) => {
        for (const entry of entries) {
          if (entry.isIntersecting) setActive(entry.target.id);
        }
      },
      { rootMargin: '-10% 0px -70% 0px' },
    );
    for (const s of sections) {
      const el = document.getElementById(s.id);
      if (el) observer.current.observe(el);
    }
    return () => observer.current?.disconnect();
    // The section list is derived from the report and does not change after mount.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  return (
    <nav
      aria-label="report sections"
      className="sticky top-0 z-10 -mx-1 flex flex-wrap gap-x-1 gap-y-1 border-b border-border bg-bg px-1 py-2"
    >
      {sections.map((s, i) => (
        <span key={s.id} className="flex items-center">
          {i > 0 && <span className="type-meta mx-1 text-faint">·</span>}
          <a
            href={`#${s.id}`}
            className={`type-meta border-b transition-colors duration-[120ms] ease-out ${
              active === s.id ? 'border-accent text-text' : 'border-transparent hover:text-text'
            }`}
          >
            {s.label}
          </a>
        </span>
      ))}
    </nav>
  );
}

// Worst four damage areas visible; the rest behind a count.
function DamageList({
  triage,
  onAnchor,
}: {
  triage: SalvageReport['triage'];
  onAnchor: (indices: number[]) => void;
}) {
  const severityRank = { heavy: 0, moderate: 1, light: 2 } as const;
  const kindRank = { structural: 0, mechanical: 1, electrical: 2, cosmetic: 3 } as const;
  const sorted = [...triage.areas].sort(
    (a, b) =>
      severityRank[a.severity] - severityRank[b.severity] || kindRank[a.kind] - kindRank[b.kind],
  );
  const lead = sorted.slice(0, 4);
  const rest = sorted.slice(4);

  const row = (area: (typeof sorted)[number], i: number) => (
    <div key={i} className="flex items-start gap-2">
      <span
        className={`mt-[7px] h-[6px] w-[6px] shrink-0 rounded-full ${
          area.kind === 'structural'
            ? 'bg-danger'
            : area.severity === 'heavy'
              ? 'bg-warn'
              : 'bg-border-strong'
        }`}
      />
      <div className="min-w-0">
        <p className="type-body max-w-[72ch]">
          <span className="font-medium capitalize">
            {area.severity} {area.kind} · {area.area}
          </span>
          <span className="text-dim"> · {area.description}</span>
        </p>
        {area.photos.length > 0 && (
          <div className="mt-1 flex gap-2">
            {area.photos.map((index) => (
              <button
                key={index}
                onClick={() => onAnchor(area.photos)}
                className="type-meta rounded-[2px] border border-border px-1.5 font-mono transition-colors duration-[120ms] ease-out hover:border-accent-dim hover:text-accent"
              >
                photo {index}
              </button>
            ))}
          </div>
        )}
      </div>
    </div>
  );

  return (
    <div className="flex flex-col gap-3">
      {lead.map(row)}
      {rest.length > 0 && (
        <details className="group">
          <summary className="type-meta cursor-pointer list-none [&::-webkit-details-marker]:hidden">
            {rest.length} lighter area{rest.length === 1 ? '' : 's'}{' '}
            <span className="text-accent group-open:hidden">expand</span>
            <span className="hidden text-accent group-open:inline">collapse</span>
          </summary>
          <div className="mt-2 flex flex-col gap-3">{rest.map((a, i) => row(a, i + 4))}</div>
        </details>
      )}
    </div>
  );
}
