import type { EngineEntry } from './types';

// Fitments are US-market cars in our data that actually shipped with the
// engine. Cars that famously carry the engine but never sold here get
// jdmOnly: true and no fitments — the resolver reports the absence honestly.

export const ENGINES: EngineEntry[] = [
  {
    code: '2JZ',
    aliases: ['2jz-gte', '2jz-ge', '2jzgte'],
    note: 'Toyota 3.0L inline-6 (2JZ); GTE twin-turbo in the Mk4 Supra Turbo',
    cylinders: 6,
    blockType: 'L',
    displacement: 3.0,
    fitments: [
      { make: 'Toyota', modelLike: ['Supra'], yearMin: 1993, yearMax: 1998 },
      { make: 'Lexus', modelLike: ['SC300'], yearMin: 1992, yearMax: 1997 },
      { make: 'Lexus', modelLike: ['IS300'], yearMin: 2001, yearMax: 2005 },
    ],
  },
  {
    code: '1JZ',
    aliases: ['1jz-gte'],
    note: 'Toyota 2.5L inline-6 (1JZ), JDM only (Chaser, Soarer, Supra Mk3 JDM); no US-market car shipped with it',
    cylinders: 6,
    blockType: 'L',
    displacement: 2.5,
    jdmOnly: true,
    fitments: [],
  },
  {
    code: 'RB26',
    aliases: ['rb26dett'],
    note: 'Nissan 2.6L twin-turbo inline-6 (RB26DETT), Skyline GT-R R32–R34, JDM only; no US-market car shipped with it',
    cylinders: 6,
    blockType: 'L',
    displacement: 2.6,
    jdmOnly: true,
    fitments: [],
  },
  {
    code: 'LS1',
    note: 'GM 5.7L V8 (LS1), Gen III small block',
    cylinders: 8,
    blockType: 'V',
    displacement: 5.7,
    fitments: [
      { make: 'Chevrolet', modelLike: ['Corvette'], yearMin: 1997, yearMax: 2004 },
      { make: 'Chevrolet', modelLike: ['Camaro'], yearMin: 1998, yearMax: 2002 },
    ],
  },
  {
    code: 'LS3',
    note: 'GM 6.2L V8 (LS3)',
    cylinders: 8,
    blockType: 'V',
    displacement: 6.2,
    fitments: [
      { make: 'Chevrolet', modelLike: ['Corvette'], yearMin: 2008, yearMax: 2013 },
      { make: 'Chevrolet', modelLike: ['Camaro'], yearMin: 2010, yearMax: 2015 },
    ],
  },
  {
    code: 'LS6',
    note: 'GM 5.7L V8 (LS6), C5 Z06',
    cylinders: 8,
    blockType: 'V',
    displacement: 5.7,
    fitments: [
      {
        make: 'Chevrolet',
        modelLike: ['Corvette'],
        yearMin: 2001,
        yearMax: 2004,
        trimContains: ['Z06'],
      },
    ],
  },
  {
    code: 'LS7',
    note: 'GM 7.0L V8 (LS7), C6 Z06',
    cylinders: 8,
    blockType: 'V',
    displacement: 7.0,
    fitments: [
      {
        make: 'Chevrolet',
        modelLike: ['Corvette'],
        yearMin: 2006,
        yearMax: 2013,
        trimContains: ['Z06'],
      },
    ],
  },
  {
    code: 'LT1',
    note: 'GM 6.2L V8 (LT1, Gen V) in C7/Camaro SS; the 1992–1996 5.7L Gen II shares the name',
    cylinders: 8,
    blockType: 'V',
    fitments: [
      { make: 'Chevrolet', modelLike: ['Corvette'], yearMin: 2014, yearMax: 2019 },
      { make: 'Chevrolet', modelLike: ['Camaro'], yearMin: 2016, yearMax: 2024 },
    ],
  },
  {
    code: 'LT4',
    note: 'GM 6.2L supercharged V8 (LT4)',
    cylinders: 8,
    blockType: 'V',
    displacement: 6.2,
    fitments: [
      {
        make: 'Chevrolet',
        modelLike: ['Corvette'],
        yearMin: 2015,
        yearMax: 2019,
        trimContains: ['Z06'],
      },
      {
        make: 'Chevrolet',
        modelLike: ['Camaro'],
        yearMin: 2017,
        yearMax: 2024,
        trimContains: ['ZL1'],
      },
    ],
  },
  {
    code: 'LT5',
    note: 'Two ZR1 engines share the name: 1990–1995 C4 ZR-1 5.7L DOHC, 2019 C7 ZR1 6.2L supercharged',
    cylinders: 8,
    blockType: 'V',
    fitments: [
      {
        make: 'Chevrolet',
        modelLike: ['Corvette'],
        yearMin: 1990,
        yearMax: 1995,
        trimContains: ['ZR'],
      },
      {
        make: 'Chevrolet',
        modelLike: ['Corvette'],
        yearMin: 2019,
        yearMax: 2019,
        trimContains: ['ZR1'],
      },
    ],
  },
  {
    code: 'K20',
    aliases: ['k20a', 'k20c1', 'k20z3'],
    note: 'Honda 2.0L inline-4 (K20)',
    cylinders: 4,
    blockType: 'L',
    displacement: 2.0,
    fitments: [
      { make: 'Acura', modelLike: ['RSX'], yearMin: 2002, yearMax: 2006 },
      {
        make: 'Honda',
        modelLike: ['Civic%'],
        yearMin: 2006,
        yearMax: 2011,
        trimContains: ['Si'],
      },
      {
        make: 'Honda',
        modelLike: ['Civic%'],
        yearMin: 2017,
        yearMax: 2026,
        trimContains: ['Type R'],
      },
    ],
  },
  {
    code: 'K24',
    note: 'Honda 2.4L inline-4 (K24); also Accord/TSX/CR-V',
    cylinders: 4,
    blockType: 'L',
    displacement: 2.4,
    fitments: [
      {
        make: 'Honda',
        modelLike: ['Civic%'],
        yearMin: 2012,
        yearMax: 2015,
        trimContains: ['Si'],
      },
    ],
  },
  {
    code: 'S54',
    note: 'BMW 3.2L inline-6 (S54), E46 M3',
    cylinders: 6,
    blockType: 'L',
    displacement: 3.2,
    fitments: [{ make: 'BMW', modelLike: ['M3'], yearMin: 2001, yearMax: 2006 }],
  },
  {
    code: 'S65',
    note: 'BMW 4.0L V8 (S65), E90/E92 M3',
    cylinders: 8,
    blockType: 'V',
    displacement: 4.0,
    fitments: [{ make: 'BMW', modelLike: ['M3'], yearMin: 2008, yearMax: 2013 }],
  },
  {
    code: 'N54',
    note: 'BMW 3.0L twin-turbo inline-6 (N54)',
    cylinders: 6,
    blockType: 'L',
    displacement: 3.0,
    fitments: [
      { make: 'BMW', modelLike: ['335%'], yearMin: 2007, yearMax: 2010 },
      { make: 'BMW', modelLike: ['135i'], yearMin: 2008, yearMax: 2010 },
    ],
  },
  {
    code: 'B58',
    note: 'BMW 3.0L turbo inline-6 (B58); also the Mk5 Supra engine',
    cylinders: 6,
    blockType: 'L',
    displacement: 3.0,
    fitments: [
      { make: 'Toyota', modelLike: ['GR Supra'], yearMin: 2020, yearMax: 2026 },
      { make: 'BMW', modelLike: ['340i', 'M340i%'], yearMin: 2016, yearMax: 2026 },
    ],
  },
  {
    code: 'EJ257',
    aliases: ['ej25'],
    note: 'Subaru 2.5L turbo flat-4 (EJ257), WRX STI',
    cylinders: 4,
    blockType: 'H',
    displacement: 2.5,
    fitments: [
      { make: 'Subaru', modelLike: ['WRX STI', 'WRX'], yearMin: 2004, yearMax: 2021 },
      {
        make: 'Subaru',
        modelLike: ['Impreza%'],
        yearMin: 2004,
        yearMax: 2007,
        trimContains: ['STI', 'WRX'],
      },
    ],
  },
  {
    code: '4G63',
    aliases: ['4g63t'],
    note: 'Mitsubishi 2.0L turbo inline-4 (4G63): Evo VIII/IX, DSM Eclipse/Talon turbos',
    cylinders: 4,
    blockType: 'L',
    displacement: 2.0,
    fitments: [
      {
        make: 'Mitsubishi',
        modelLike: ['Lancer%'],
        yearMin: 2003,
        yearMax: 2006,
        trimContains: ['Evolution'],
      },
      { make: 'Mitsubishi', modelLike: ['Eclipse'], yearMin: 1990, yearMax: 1999 },
      { make: 'Eagle', modelLike: ['Talon'], yearMin: 1990, yearMax: 1998 },
    ],
  },
  {
    code: 'VQ35',
    aliases: ['vq35de', 'vq35hr'],
    note: 'Nissan 3.5L V6 (VQ35)',
    cylinders: 6,
    blockType: 'V',
    displacement: 3.5,
    fitments: [
      { make: 'Nissan', modelLike: ['350Z'], yearMin: 2003, yearMax: 2008 },
      { make: 'INFINITI', modelLike: ['G35'], yearMin: 2003, yearMax: 2007 },
      { make: 'INFINITI', modelLike: ['FX35'], yearMin: 2003, yearMax: 2008 },
    ],
  },
  {
    code: 'M156',
    note: 'Mercedes-AMG 6.2L naturally aspirated V8 (M156)',
    cylinders: 8,
    blockType: 'V',
    displacement: 6.2,
    fitments: [
      { make: 'Mercedes-Benz', modelLike: ['C63 AMG'], yearMin: 2008, yearMax: 2015 },
      { make: 'Mercedes-Benz', modelLike: ['E63 AMG'], yearMin: 2007, yearMax: 2011 },
    ],
  },
  {
    code: '1LR-GUE',
    aliases: ['1lr'],
    note: 'Lexus/Yamaha 4.8L V10 (1LR-GUE), LFA only',
    cylinders: 10,
    blockType: 'V',
    displacement: 4.8,
    fitments: [{ make: 'Lexus', modelLike: ['LFA'], yearMin: 2012, yearMax: 2012 }],
  },
];
