import type { ModelWord } from './types';

// How enthusiasts name models, mapped to the exact model strings in the data.
// Validated against the eval DB like every other table. jdmOnly entries
// document absence: the resolver reports "never sold here" instead of nothing.

export const MODEL_WORDS: ModelWord[] = [
  // Toyota
  { token: 'supra', make: 'Toyota', models: ['Supra', 'GR Supra'] },
  { token: 'gr supra', make: 'Toyota', models: ['GR Supra'] },
  { token: 'celica', make: 'Toyota', models: ['Celica'] },
  { token: 'mr2', make: 'Toyota', models: ['MR2%'] },
  { token: 'gr86', make: 'Toyota', models: ['GR86'] },
  {
    token: 'ae86',
    make: 'Toyota',
    models: ['Corolla'],
    yearMin: 1984,
    yearMax: 1987,
    note: 'AE86 chassis: 1984–1987 Corolla (GT-S/SR5)',
  },
  // Porsche
  { token: '911', make: 'Porsche', models: ['911'] },
  { token: 'boxster', make: 'Porsche', models: ['Boxster', '718 Boxster'] },
  { token: 'cayman', make: 'Porsche', models: ['Cayman', '718 Cayman'] },
  { token: '944', make: 'Porsche', models: ['944'] },
  { token: '928', make: 'Porsche', models: ['928'] },
  { token: 'carrera gt', make: 'Porsche', models: ['Carrera GT'] },
  // Chevrolet
  { token: 'corvette', aliases: ['vette'], make: 'Chevrolet', models: ['Corvette'] },
  { token: 'camaro', make: 'Chevrolet', models: ['Camaro'] },
  // BMW
  { token: 'm2', make: 'BMW', models: ['M2'] },
  { token: 'm3', make: 'BMW', models: ['M3'] },
  { token: 'm4', make: 'BMW', models: ['M4'] },
  { token: 'm5', make: 'BMW', models: ['M5'] },
  { token: 'm6', make: 'BMW', models: ['M6'] },
  { token: 'm8', make: 'BMW', models: ['M8'] },
  { token: '1m', aliases: ['1 series m'], make: 'BMW', models: ['1 Series M'] },
  { token: 'z3', make: 'BMW', models: ['Z3'] },
  { token: 'z4', make: 'BMW', models: ['Z4'] },
  { token: 'z8', make: 'BMW', models: ['Z8'] },
  // Volkswagen
  { token: 'golf', make: 'Volkswagen', models: ['Golf%'] },
  { token: 'golf r', make: 'Volkswagen', models: ['Golf R'] },
  { token: 'gti', make: 'Volkswagen', models: ['GTI'] },
  { token: 'jetta', make: 'Volkswagen', models: ['Jetta%'] },
  { token: 'rabbit', make: 'Volkswagen', models: ['Rabbit'] },
  { token: 'corrado', make: 'Volkswagen', models: ['Corrado'] },
  { token: 'passat', make: 'Volkswagen', models: ['Passat'] },
  { token: 'beetle', make: 'Volkswagen', models: ['Beetle'] },
  // Honda / Acura
  { token: 'civic', make: 'Honda', models: ['Civic%'] },
  { token: 'crx', make: 'Honda', models: ['CRX'] },
  { token: 's2000', aliases: ['s2k'], make: 'Honda', models: ['S2000'] },
  { token: 'prelude', make: 'Honda', models: ['Prelude'] },
  { token: 'del sol', make: 'Honda', models: ['Civic del Sol'] },
  { token: 'integra', make: 'Acura', models: ['Integra'] },
  { token: 'rsx', make: 'Acura', models: ['RSX'] },
  { token: 'nsx', make: 'Acura', models: ['NSX'] },
  // Mazda
  { token: 'miata', aliases: ['mx5', 'mx-5'], make: 'Mazda', models: ['MX-5%', 'Miata'] },
  { token: 'rx7', aliases: ['rx-7'], make: 'Mazda', models: ['RX-7'] },
  { token: 'rx8', aliases: ['rx-8'], make: 'Mazda', models: ['RX-8'] },
  // Nissan / Datsun
  { token: 'gtr', aliases: ['gt-r'], make: 'Nissan', models: ['GT-R'] },
  {
    token: 'skyline',
    make: 'Nissan',
    models: ['Skyline%'],
    jdmOnly: true,
    note: 'Skyline was never sold in the US; the R35 GT-R is its successor',
  },
  {
    token: 'silvia',
    make: 'Nissan',
    models: ['Silvia%'],
    jdmOnly: true,
    note: 'Silvia was never sold in the US; the 240SX is its US cousin',
  },
  { token: '350z', make: 'Nissan', models: ['350Z'] },
  { token: '370z', make: 'Nissan', models: ['370Z'] },
  { token: '300zx', make: 'Nissan', models: ['300ZX'] },
  { token: '240sx', make: 'Nissan', models: ['240SX'] },
  { token: '240z', make: 'Datsun', models: ['240Z'] },
  { token: '280z', make: 'Datsun', models: ['280Z'] },
  { token: '280zx', make: 'Datsun', models: ['280ZX'] },
  { token: '510', make: 'Datsun', models: ['510'] },
  // Subaru
  { token: 'wrx', make: 'Subaru', models: ['WRX%'] },
  { token: 'impreza', make: 'Subaru', models: ['Impreza'] },
  { token: 'brz', make: 'Subaru', models: ['BRZ'] },
  // Mitsubishi / Eagle
  { token: 'lancer', make: 'Mitsubishi', models: ['Lancer'] },
  { token: 'eclipse', make: 'Mitsubishi', models: ['Eclipse'] },
  { token: '3000gt', make: 'Mitsubishi', models: ['3000GT'] },
  { token: 'talon', make: 'Eagle', models: ['Talon'] },
  // Audi ("tt" is deliberately absent: it needs context — Audi TT vs twin turbo)
  { token: 'r8', make: 'Audi', models: ['R8'] },
  { token: 'rs3', make: 'Audi', models: ['RS3'] },
  { token: 'rs4', make: 'Audi', models: ['RS4'] },
  { token: 'rs5', make: 'Audi', models: ['RS5%'] },
  { token: 'rs6', make: 'Audi', models: ['RS6%'] },
  { token: 'rs7', make: 'Audi', models: ['RS7%'] },
  { token: 's3', make: 'Audi', models: ['S3'] },
  { token: 's4', make: 'Audi', models: ['S4'] },
  { token: 's5', make: 'Audi', models: ['S5%'] },
  { token: 's6', make: 'Audi', models: ['S6'] },
  { token: 's7', make: 'Audi', models: ['S7%'] },
  { token: 'a3', make: 'Audi', models: ['A3%'] },
  { token: 'a4', make: 'Audi', models: ['A4%'] },
  { token: 'a6', make: 'Audi', models: ['A6%'] },
  { token: 'a7', make: 'Audi', models: ['A7%'] },
  { token: 'tts', make: 'Audi', models: ['TTS'] },
  { token: 'tt rs', aliases: ['ttrs'], make: 'Audi', models: ['TT RS%'] },
  // Mercedes
  { token: 'c63', make: 'Mercedes-Benz', models: ['C63 AMG%'] },
  { token: 'e63', make: 'Mercedes-Benz', models: ['E63 AMG%'] },
  { token: 'e55', make: 'Mercedes-Benz', models: ['E55 AMG'] },
  { token: 'sl55', make: 'Mercedes-Benz', models: ['SL55 AMG'] },
  { token: 'amg gt', make: 'Mercedes-Benz', models: ['AMG GT%'] },
  { token: '190e', make: 'Mercedes-Benz', models: ['190E'] },
  // Dodge
  { token: 'challenger', make: 'Dodge', models: ['Challenger'] },
  { token: 'charger', make: 'Dodge', models: ['Charger'] },
  { token: 'viper', make: 'Dodge', models: ['Viper'] },
  { token: 'neon', make: 'Dodge', models: ['Neon'] },
  // Ford
  { token: 'mustang', make: 'Ford', models: ['Mustang'] },
  { token: 'f150', aliases: ['f-150'], make: 'Ford', models: ['F-150'] },
  { token: 'focus', make: 'Ford', models: ['Focus'] },
  { token: 'fiesta', make: 'Ford', models: ['Fiesta'] },
  // Alfa Romeo
  { token: 'giulia', make: 'Alfa Romeo', models: ['Giulia'] },
  { token: 'stelvio', make: 'Alfa Romeo', models: ['Stelvio'] },
  { token: '4c', make: 'Alfa Romeo', models: ['4C'] },
  // Lexus
  { token: 'lfa', make: 'Lexus', models: ['LFA'] },
  { token: 'is300', make: 'Lexus', models: ['IS300'] },
  { token: 'sc300', make: 'Lexus', models: ['SC300'] },
  { token: 'sc400', make: 'Lexus', models: ['SC400'] },
  { token: 'is f', aliases: ['isf'], make: 'Lexus', models: ['IS F'] },
  { token: 'rc f', aliases: ['rcf'], make: 'Lexus', models: ['RC F'] },
  { token: 'gs f', aliases: ['gsf'], make: 'Lexus', models: ['GS F'] },
  // INFINITI
  { token: 'g35', make: 'INFINITI', models: ['G35'] },
  { token: 'g37', make: 'INFINITI', models: ['G37'] },
  { token: 'fx35', make: 'INFINITI', models: ['FX35'] },
  // Others
  { token: 'stinger', make: 'Kia', models: ['Stinger'] },
  { token: 'gallardo', make: 'Lamborghini', models: ['Gallardo'] },
  { token: 'huracan', make: 'Lamborghini', models: ['Huracan'] },
];

// Colloquial make names → the exact make string in the data.
export const MAKE_WORDS: Record<string, string> = {
  porsche: 'Porsche',
  bmw: 'BMW',
  bimmer: 'BMW',
  toyota: 'Toyota',
  chevrolet: 'Chevrolet',
  chevy: 'Chevrolet',
  volkswagen: 'Volkswagen',
  vw: 'Volkswagen',
  honda: 'Honda',
  acura: 'Acura',
  mazda: 'Mazda',
  nissan: 'Nissan',
  datsun: 'Datsun',
  subaru: 'Subaru',
  subie: 'Subaru',
  mitsubishi: 'Mitsubishi',
  mitsu: 'Mitsubishi',
  audi: 'Audi',
  mercedes: 'Mercedes-Benz',
  'mercedes-benz': 'Mercedes-Benz',
  benz: 'Mercedes-Benz',
  merc: 'Mercedes-Benz',
  dodge: 'Dodge',
  ford: 'Ford',
  alfa: 'Alfa Romeo',
  'alfa romeo': 'Alfa Romeo',
  lexus: 'Lexus',
  infiniti: 'INFINITI',
  kia: 'Kia',
  lamborghini: 'Lamborghini',
  lambo: 'Lamborghini',
  volvo: 'Volvo',
  eagle: 'Eagle',
  shelby: 'Shelby',
};
